<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYKYa2gY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYKYa2gY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYKYa2gY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYKYa2gY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYKYa2gY\App_KernelDevDebugContainer([
    'container.build_hash' => 'YKYa2gY',
    'container.build_id' => 'e0c208f3',
    'container.build_time' => 1680546176,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYKYa2gY');
