<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOCmv7Ax\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOCmv7Ax/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOCmv7Ax.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOCmv7Ax\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOCmv7Ax\App_KernelDevDebugContainer([
    'container.build_hash' => 'OCmv7Ax',
    'container.build_id' => '05703f45',
    'container.build_time' => 1680790115,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOCmv7Ax');
