<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUvcDChk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUvcDChk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUvcDChk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUvcDChk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUvcDChk\App_KernelDevDebugContainer([
    'container.build_hash' => 'UvcDChk',
    'container.build_id' => '488e6374',
    'container.build_time' => 1680778744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUvcDChk');
